

version: "3.7"
# services:
#   docs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     ports:
#       - 7000:8000
#     volumes:
#       - ./:/app

services:
  lottery_app_api:
    container_name: lottery_app_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:8000
    environment:
      - NODE_ENV=development

